log:
  name: '20210916'
  version: 'test_1'
  log_graph: False

dataset:
  train_data: ["ZoomRaw2RGB", ]              # DIV2K, BSD500, ...
  test_data: ['ZoomRaw2RGB']                  # ['Set5', 'Set14', 'BSD100', 'Urban100', 'Manga109']
  save_test_img: True
  test_only: False
  batch_size: 8
  shuffle: True
  num_workers: 16
  args:
    dir: "dataset"
    patch_size: 96
    scale: 4
    rgb_range: 1

model:
  net: 'HAN_RAW'
  xcolor: True
  pretrain: False       
  n_resgroups: 10
  n_resblocks: 20
  n_feats: 64
  reduction: 16
  n_colors: 3
  res_scale: 1
  corrector:
    matching_type: 'correlation'

trainer:                       
  gpus: 1
  max_epochs: 450
  accumulate_grad_batches: 2
  gradient_clip_val: 0.5
  #check_val_every_n_epoch: 2
  limit_val_batches: 0.5
  #profiler: "pytorch"
  #log_gpu_memory: "all"
  #fast_dev_run: 1          # This is for test - it will cause error for validation step

  #################### best ckpt ###################  # ckpt should accord with scale and xcolor settings

  resume_from_checkpoint : "logs/ocolor/log_2207151847/checkpoints/epoch=446-step=12963.ckpt"  # with color corrector / x4
  # resume_from_checkpoint : "logs/ocolorx8/log_2207201010/checkpoints/epoch=415-step=12064.ckpt"  # with color corrector / x8
  # resume_from_checkpoint : "logs/xcolor/log_2207141442/checkpoints/epoch=321-step=4830.ckpt"  # without color corrector / x4
  # resume_from_checkpoint : "logs/xcolorx8/log_2207250917/checkpoints/epoch=435-step=12644.ckpt"  # without color corrector / x8

  ##################################################

callback:
  save_top_k: 100
  earlly_stop_patience: 100
  min_delta: 1.0e-4

optimizer:
  name: 'adam'
  learning_rate: 1.0e-4
  weight_decay: 5.0e-3
  momentum: 0.9                         # only work for SGD

scheduler:
  name: 'multistep'
  min_lr: 1.0e-8
  multistep: [150, 300, 350, 400]   # work for MultiStepLR
  patience: 10                          # work for RedcueLROnPlateau
  cooldown: 5
  factor: 0.1                           # lr schedule decay factor
